support-project/knowledge

src/main/webapp/WEB-INF/views/open/knowledge/view.jsp
=> 記事ページ上のタイトルで一部の文字が正しく表示されない問題

src/main/resources/appresource.properties, src/main/resources/appresource_ja.properties, src/main/webapp/WEB-INF/views/open/knowledge/search.jsp, src/main/webapp/WEB-INF/views/open/tag/dialog.jsp, src/main/webapp/WEB-INF/views/protect/knowledge/view_add.jsp, src/main/webapp/WEB-INF/views/protect/knowledge/view_edit.jsp
=> 「Tag Select」をロケール ファイルに追加

src/main/java/org/support/project/knowledge/control/protect/GroupControl.java
404 Not foundになるためコントローラのHTTPメソッドをPostに変更してみました。
ご検討よろしくお願いいたします。
=> #95 グループ削除のHTTPメソッドを@Postに変更

src/main/java/org/support/project/knowledge/bat/NotifyMailBat.java, src/main/java/org/support/project/knowledge/logic/NotifyLogic.java, src/main/webapp/WEB-INF/views/commons/layout/commonScripts.jsp
デスクトップ通知は3秒で消えるようにして、通知をクリックするとそのナレッジを表示するように変更
=> #101 デスクトップ通知は3秒で消えるようにして、通知をクリックするとそのナレッジを表示するように変更

bower.json, src/main/java/org/support/project/knowledge/control/admin/TemplateControl.java, src/main/resources/appresource.properties, src/main/resources/appresource_ja.properties, src/main/webapp/WEB-INF/views/admin/template/list.jsp, src/main/webapp/WEB-INF/views/admin/template/view_add.jsp, src/main/webapp/WEB-INF/views/admin/template/view_edit.jsp, src/main/webapp/WEB-INF/views/commons/layout/commonNavbar.jsp, src/main/webapp/WEB-INF/views/protect/knowledge/view_add.jsp, src/main/webapp/WEB-INF/views/protect/knowledge/view_edit.jsp, src/main/webapp/js/knowledge-edit.js
要求の全てでは無いけど、使えるところまでできたのでいったんマージしようかと思います。
- 作ったところ
- 管理者による、ナレッジ登録のテンプレート一覧表示とテンプレートの説明を登録    
- 登録時にテンプレートの説明を表示
=> #89 投稿時の注意メッセージの表示

src/main/webapp/WEB-INF/views/protect/group/groups.jsp, src/main/webapp/WEB-INF/views/protect/group/mygroups.jsp
#115 の対応になります。
所属しているグループの一覧、グループ一覧で記事数をバッジで表示するようにしました。
=> グループ一覧でグループの記事数を表示するように

pom.xml, src/main/resources/appresource.properties, src/main/resources/appresource_ja.properties, src/test/java/org/support/project/knowledge/logic/MarkdownLogicTest.java
Release 0.6.0 正式版 発行のため、developの内容をmasterにマージする
=> Edit Release v0.6.0

pom.xml, src/main/java/org/support/project/knowledge/logic/MarkdownLogic.java
オプションを追加して改行を改行として解釈されるようにしました。
=> #139 markedjの更新とオプションの追加

src/test/resources/org/support/project/knowledge/logic/markdown/result-markdj-1.txt
=> MarkdownLogicのテストの期待値修正

src/main/webapp/css/markdown.css
=> #144 インラインコードの場合に、文字が長い場合に折り返すよう変更

src/main/webapp/WEB-INF/views/commons/layout/commonNavbar.jsp, src/main/webapp/WEB-INF/views/open/knowledge/list.jsp
@koda-masaru さん
返信が送れてしまい、すみません。
レイアウト案、気に入っていただけて、嬉しいです。
#169 を受けて、PRを作り直しました。これで良いでしょうか？
そして、申し訳ないのですが、指示の具体的な意味が掴めませんでした。
今までの助言をもとに以下のようにすれば良いのか、と解釈したのですが、意図された通りでしょうか？
①リモートの最新情報を取得
```
C:\Users\user1\Desktop\knowledge>git fetch upstream
```
② ブランチをjohに切り替える
```
C:\Users\user1\Desktop\knowledge>git checkout joh
```
③upstream/feature/issue170_change_layout に統合する
```
C:\Users\user1\Desktop\knowledge>git rebase upstream/feature/issue170_change_layout
```
④ pushする
```
C:\Users\user1\Desktop\knowledge>git push origin joh
```
⑤ PRを出す
=> （再2）ヘッダのビュー変更と記事リストのビュー変更

src/main/webapp/css/knowledge-list.css, src/main/webapp/js/knowledge-list.js
jsは直前のブロックもコメントアウトで残されていたので、上に習って残しました。
が、コメントアウトした部分は消してしまっても良いと思います。
=> リスト表示 hover で表示がずれないようにした

src/main/java/org/support/project/knowledge/control/open/ThemaControl.java, src/main/resources/appresource.properties, src/main/resources/appresource_ja.properties, src/main/webapp/WEB-INF/views/commons/layout/commonHeader.jsp, src/main/webapp/WEB-INF/views/open/thema/highlight.jsp, src/main/webapp/WEB-INF/views/open/thema/list.jsp, src/main/webapp/css/markdown.css, src/main/webapp/js/knowledge-common.js
コードハイライトのスタイルも変更してみました。
（デフォルト、ダーク系のスタイル）
=> #188 Code Highlight のスタイルも設定可能にした

src/main/webapp/WEB-INF/views/open/knowledge/common_list.jsp, src/main/webapp/WEB-INF/views/open/knowledge/common_sub_list.jsp, src/main/webapp/WEB-INF/views/open/knowledge/list.jsp, src/main/webapp/WEB-INF/views/open/knowledge/show_history.jsp, src/main/webapp/css/knowledge-list.css
=> #196 一覧から詳細画面へ遷移する際に、Javascriptを使わず、普通のアンカータグのリンクを使うようにする

bower.json, src/main/webapp/WEB-INF/views/commons/layout/commonHeader.jsp, src/main/webapp/WEB-INF/views/commons/layout/commonScripts.jsp, src/main/webapp/js/knowledge-edit.js
notify.js のバージョンを最新から、前に使っていたものに戻しました
=> ナレッジの登録／更新時にnotify.js でエラーが発生するので、バージョンを動作できていたバージョンに戻す

src/main/webapp/WEB-INF/views/open/knowledge/common_list.jsp, src/main/webapp/css/knowledge-list.css
一覧画面の表示をイジって、テーマをダークにした場合なども表示が変にならないように調整しました。
=> ナレッジの一覧のhoverが、テーマをダーク系に変更しても変にならないように調整した

src/main/java/org/support/project/knowledge/control/open/KnowledgeControl.java, src/main/java/org/support/project/knowledge/logic/TargetLogic.java, src/main/webapp/WEB-INF/views/open/knowledge/common_list.jsp, src/main/webapp/WEB-INF/views/open/knowledge/view.jsp, src/main/webapp/css/common.css, src/main/webapp/css/knowledge-edit.css, src/main/webapp/css/knowledge-list.css
#177 の対応になります。
一覧ページ、詳細ページのtag、groupからそのまま絞り込んだ一覧ページに遷移できるようにしました。
=> #177 一覧ページや詳細ページのtag、groupにリンクをつけた

src/main/webapp/WEB-INF/views/open/knowledge/view.jsp, src/main/webapp/css/knowledge-view.css
=> #205 ナレッジ表示画面を調整してみた

src/main/webapp/WEB-INF/views/open/knowledge/view.jsp
=> #222 記事詳細画面のレイアウト崩れの修正

pom.xml
support-project/markedj に本家の変更を取り込んだのでknowledge側のバージョン変更しました。
ご確認よろしくお願いします。
=> markedjのバージョンを1.0.6-SNAPSHOTに変更

src/main/webapp/WEB-INF/views/protect/config/index.jsp
=> #227 メニューの一覧に、グループ設定へのリンクを追加

src/main/webapp/WEB-INF/views/open/knowledge/view.jsp, src/main/webapp/css/knowledge-view.css, src/main/webapp/css/markdown.css
#230 より。
添付ファイル件のコメントアウト作業を取り消しました。
よろしくお願いします。
=> (再)記事本文の視認性と可読性を上げる

src/main/webapp/WEB-INF/views/commons/layout/commonNavbar.jsp, src/main/webapp/css/common.css
- Navbarに名前を表示してみたところ、名前が長いとレイアウトが崩れるので、名前は表示しない
- ログイン前／後でメニューボタンを変化させることで、状態を表すようにした
- ボタンの色合いを変更
- ログイン後、メニューの中にログインしているユーザの情報（名前など）を表示
=> #224 ログインしているかをNavbarのメニューでわかるようにした

bower.json
Reverts support-project/knowledge#243
間違えて master にマージしていた。
=> Revert "#240 タグ入力のライブラリを以前動作させていたバージョンに戻した"

src/main/java/org/support/project/knowledge/control/open/KnowledgeControl.java, src/main/java/org/support/project/knowledge/logic/KeywordLogic.java, src/main/webapp/WEB-INF/views/open/knowledge/common_list.jsp
=> 一覧上でグループやタグを指定してる場合にクエリをキーワード検索に入れるように

src/main/java/org/support/project/knowledge/control/open/KnowledgeControl.java, src/main/webapp/WEB-INF/views/open/knowledge/common_sub_list.jsp, src/main/webapp/WEB-INF/views/open/knowledge/list.jsp, src/main/webapp/css/knowledge-list.css
=> 一覧上でグループやタグを選択してる場合に右のメニューでハイライトするように

src/test/java/org/support/project/knowledge/dao/AccountImagesDaoTest.java, src/test/java/org/support/project/knowledge/dao/KnowledgesDaoTest.java, src/test/java/org/support/project/knowledge/dao/LikesDaoTest.java, src/test/java/org/support/project/knowledge/logic/KnowledgeLogicTest.java
- test in embedded mode may fail.
- If database started on server mode, the test will successful.
=> Start the H2Sql database on server mode at the start of the test.

src/main/java/org/support/project/knowledge/bat/NotifyMailBat.java, src/main/java/org/support/project/knowledge/control/admin/ProxyControl.java, src/main/java/org/support/project/knowledge/control/admin/TemplateControl.java, src/main/java/org/support/project/knowledge/control/open/AccountControl.java, src/main/java/org/support/project/knowledge/deploy/InitDB.java, src/main/java/org/support/project/knowledge/logic/HttpLogic.java, src/main/java/org/support/project/knowledge/logic/KnowledgeLogic.java, src/main/java/org/support/project/knowledge/parser/impl/TikaParser.java
This pull request is focused on resolving occurrences of Sonar rules
squid:S1854 - Dead stores should be removed.
https://dev.eclipse.org/sonar/coding_rules#q=squid%3AS1854
George Kankava
=> squid:S1854 - Dead stores should be removed

src/main/java/org/support/project/knowledge/bat/AbstractBat.java, src/main/java/org/support/project/knowledge/bat/CreateExportDataBat.java, src/main/java/org/support/project/knowledge/bat/DataTransferBat.java, src/main/java/org/support/project/knowledge/bat/FileParseBat.java, src/main/java/org/support/project/knowledge/bat/KnowledgeFileClearBat.java, src/main/java/org/support/project/knowledge/bat/MailSendBat.java, src/main/java/org/support/project/knowledge/bat/NotifyMailBat.java, src/main/java/org/support/project/knowledge/bat/ReIndexingBat.java, src/main/java/org/support/project/knowledge/bat/WebhookBat.java
This pull request is focused on resolving occurrence of Sonar rule
squid:S00105 - Tabulation characters should not be used.
https://dev.eclipse.org/sonar/rules/show/squid%3AS00105
George Kankava
=> squid:S00105 - Tabulation characters should not be used

src/main/java/org/support/project/knowledge/dao/KnowledgesDao.java, src/main/java/org/support/project/knowledge/dao/NotifyConfigsDao.java, src/main/java/org/support/project/knowledge/dao/TagsDao.java, src/main/java/org/support/project/knowledge/dao/TemplateMastersDao.java, src/main/java/org/support/project/knowledge/dao/WebhookConfigsDao.java
This pull request is focused on resolving occurrence of Sonar rule
squid:S1066 - Collapsible "if" statements should be merged.
https://dev.eclipse.org/sonar/rules/show/squid:S1066
George Kankava
=> squid:S1066 - Collapsible "if" statements should be merged

src/main/java/org/support/project/knowledge/logic/KnowledgeLogic.java
- updateメソッドを呼ぶと、自動的に更新日時を更新するようになっている
- physicalUpdateメソッドは、生のデータ操作で更新日時などの自動更新はしないようになっている
=> #311 いいね！やコメントの件数の集計メソッドでナレッジ情報を集計する際に、更新日時が変化しないようにした

src/main/resources/appresource.properties, src/main/resources/appresource_ja.properties, src/main/webapp/WEB-INF/views/protect/knowledge/markdown.jsp, src/main/webapp/css/knowledge-edit.css, src/main/webapp/js/knowledge-edit.js
=> #181 Markdownの参考ページは、上部にMarkdownのテキスト、下部にそのHTMLを表示するようにした

src/main/resources/org/support/project/knowledge/webhook/comments.json, src/main/resources/org/support/project/knowledge/webhook/knowledges.json
=> Webhookのリソースファイルの時間フォーマットを修正

src/main/webapp/css/markdown.css
- font size of blockquote to small
=> #281 modify css style

src/main/java/org/support/project/knowledge/control/protect/NotifyControl.java
#346 の対応。
メール通知／デスクトップ通知を選択したのにもかかわらず、
通知する種類を選択しなかった場合は、デフォルトONにする。
=> #346 modify default value of notify config.

src/main/java/org/support/project/knowledge/logic/AddUserProcessLogic.java, src/main/resources/appconfig.xml
- ユーザー登録時に、メールの通知設定をデフォルトでONにします
- 「メール届かないんだけど」という問い合わせがけっこうあるので、、、
- デフォルトONにしておき、いらない場合にOFFにしてもらう運用に変更
- オプトインからオプトアウトへ
=> #356 Set the notification flag when user registration.

src/main/java/org/support/project/knowledge/logic/KnowledgeLogic.java, src/main/java/org/support/project/knowledge/websocket/ReindexingEndpoint.java
#352 のデバッグしていた時に見つけたエラーを修正
- インデックスの再作成処理の中でエラーが出るときがあったので修正
=> fix error on reindexing

src/main/java/org/support/project/knowledge/logic/DataTransferLogic.java, src/main/java/org/support/project/knowledge/websocket/DataTransferEndpoint.java, src/main/webapp/WEB-INF/views/admin/database/connection.jsp
#352 の対応
- コピー元からコピー先のDBにデータをコピーする処理にログを追加
- コピー元のDBのマイグレーションが正しく完了していないと、エラーが発生する（？）と思われるので、マイグレーションを実行するように修正した
=> add logging to data transfer method.

src/main/java/org/support/project/knowledge/control/admin/DatabaseControl.java, src/main/java/org/support/project/knowledge/control/admin/SystemConfigControl.java, src/main/resources/appresource.properties, src/main/resources/appresource_ja.properties, src/main/webapp/WEB-INF/views/admin/database/connection.jsp, src/main/webapp/WEB-INF/views/admin/systemconfig/index.jsp
システム設定メニューで、データベースをPostgresに変更した方が良い
というメッセージを表示
=> #40 add recommend message of change database

pom.xml
#370 のエラーは確認できなかったが、本家のMarkdownパーサーのほうでテーブルの
記述のパース部分が更新されていたので、それを取り込むためバージョンアップする。
ついでに #367 の対応も行う予定。
=> change markej version

bower.json, src/main/java/org/support/project/knowledge/control/open/KnowledgeControl.java, src/main/resources/appresource.properties, src/main/resources/appresource_ja.properties, src/main/webapp/WEB-INF/views/open/knowledge/view.jsp, src/main/webapp/js/knowledge-view.js
=> #374 Add clip url button on knowledge view page

README.md
Reverts support-project/knowledge#381
=> Revert "Add button to deploy Azure"

pom.xml
=> Develop -> Master

pom.xml, src/main/java/org/support/project/knowledge/control/open/AccountControl.java, src/main/resources/appresource.properties, src/main/resources/appresource_ja.properties
=> #387 fix user page's error

src/main/java/org/support/project/knowledge/deploy/v1_5_0/Migrate_1_5_0.java, src/main/java/org/support/project/knowledge/logic/MailhookLogic.java
メールから投稿時に、投稿者の検索をメールアドレスへ変更。
（ユーザのキーは、通常メールアドレスだけど、LDAPログインを使った場合、
メールアドレスで無いこともある）
=> #86 Change knowledge register user

src/main/java/org/support/project/knowledge/logic/MailhookLogic.java
メールから投稿の機能の際に、メールに添付ファイルがついていたら、
Knowledgeにもそのファイルを添付します。
=> #394 Add file if attach file exist.

src/main/resources/appresource.properties, src/main/resources/appresource_ja.properties
=> #417 Add message resource for label

src/main/java/org/support/project/knowledge/bat/FileParseBat.java
#415 ファイルの中身解析時のインデックス生成時に、アクセス権を適切に追加するように修正
=> Add access role to protected user at file parse process.

src/main/java/org/support/project/knowledge/logic/KnowledgeLogic.java
#256 共同編集者を保存する際、登録者とは違うユーザが保存すると、自分を「編集者」から削除してしまっていたので修正
=> Fix process to save a editor

src/main/resources/appresource.properties, src/main/resources/appresource_ja.properties, src/main/webapp/WEB-INF/views/open/language/index.jsp, src/main/webapp/WEB-INF/views/open/thema/list.jsp, src/main/webapp/WEB-INF/views/protect/account/index.jsp, src/main/webapp/WEB-INF/views/protect/config/index.jsp, src/main/webapp/WEB-INF/views/protect/notify/index.jsp, src/main/webapp/WEB-INF/views/protect/notify/test.jsp
=> #426 Modify config page design

src/main/java/org/support/project/knowledge/control/admin/UsersControl.java, src/main/resources/appresource.properties, src/main/resources/appresource_ja.properties, src/main/webapp/WEB-INF/views/admin/users/view_edit.jsp
#368 管理者がユーザを削除する際に、今まで登録したデータを削除する／しないを選択可能にした
=> #368 Add select keep knowledge when user remove by admin

src/main/java/org/support/project/knowledge/control/open/KnowledgeControl.java, src/main/java/org/support/project/knowledge/searcher/impl/LuceneSearcher.java, src/main/resources/appresource.properties, src/main/resources/appresource_ja.properties
#439 #219 検索キーワードによるエラーが発生した場合、エラー画面に遷移せず、
検索結果が0件の表示に遷移する
=> #439 Add error handle for search query.

src/main/resources/appresource.properties, src/main/resources/appresource_ja.properties
=> #449 Add link to FontAwesome

src/main/webapp/js/knowledge-view-template.js
#443 Bookmarkの場合に、URLを大きなサイズで表示
=> #443 Change the display size of the bookmark of URL

LICENSE.md, src/main/resources/appresource.properties, src/main/resources/appresource_ja.properties, src/main/webapp/WEB-INF/views/open/license/index.jsp
Updated the version and add a license for additional library
=> Release v1.6.0.pre2

src/main/java/org/support/project/knowledge/control/admin/UsersControl.java, src/main/resources/appresource.properties, src/main/resources/appresource_ja.properties, src/main/webapp/WEB-INF/views/admin/users/accept_list.jsp
#498 の承認待ちユーザを削除する機能を追加しました。
画面イメージは下記になります。
=> Add ability to delete approval pending user

src/main/webapp/js/knowledge-edit.js
=> Fixed #494 Do not submit by pressing enter when input title

src/main/java/org/support/project/knowledge/bat/FileParse.java, src/main/java/org/support/project/knowledge/listener/CronListener.java, src/main/java/org/support/project/knowledge/parser/impl/PdfSlideShowParserOnPdfbox.java, src/main/java/org/support/project/knowledge/parser/impl/PptxSlideShowParser.java
スライドのパースの中で、out of memoryが発生。
画像抽出のライブラリ内で発生しているため、
起動時に指定する最大メモリを増やすしか方法が無さそう。
そこで、最大メモリを指定してみた。
=> Add config of memory size on java batch program.

src/main/java/org/support/project/knowledge/control/protect/KnowledgeControl.java, src/main/java/org/support/project/knowledge/logic/KnowledgeLogic.java, src/main/java/org/support/project/knowledge/vo/KnowledgeData.java, src/main/resources/appresource.properties, src/main/resources/appresource_ja.properties, src/main/webapp/WEB-INF/views/protect/knowledge/edit.jsp, src/main/webapp/js/knowledge-edit.js
属性情報のみを更新した場合、更新と判定しないように変更した。
（更新と判定されるのは、タイトル及び本文を更新した場合のみ）
=> #517 Add a function to judge whether to send update notification

src/main/webapp/js/account.js
アカウント画像のプレビュー＆範囲選択のダイアログのタイトルを修正
=> #569 Fix Crop dialog title label.

src/main/webapp/WEB-INF/views/protect/knowledge/partials/partials-edit-meta.jsp
Error occurs on trying to write new article.
Environment:
Ubuntu 16.04.2 tomcat7
=> fix "Cannot cast from Object to int".

Third_party_license.txt, bower.json, gulpfile.js, src/main/webapp/WEB-INF/views/open/knowledge/history.jsp, src/main/webapp/WEB-INF/views/open/license/index.jsp
はじめまして。
いつもKnowledgeを使わせていただいています。
記事の更新履歴の差分を、GitHubのように表示できると便利かと思い実装してみました。
以下のJSライブラリーを使用しています。
- diff2html
- License: [MIT] https://github.com/rtfpessoa/diff2html#license
- project-url: https://diff2html.xyz/
- jsdiff
- License: [BSD License] https://github.com/kpdecker/jsdiff/blob/master/LICENSE
- project-url: https://github.com/kpdecker/jsdiff
よろしければご確認をお願いいたします。
=> Modify history page to change the diff function.

src/main/webapp/WEB-INF/views/protect/account/targets.jsp
ユーザメニューの公開範囲のデフォルト設定の初期値を「非公開」にした
=> #740 Change default publication range on user menu

src/main/webapp/WEB-INF/views/commons/layout/commonNavbar.jsp
下書き一覧とストックが階層深くなってしまいどこにあるのかわかりにくいのでナビバーを変更してみました。
デザイン部分を変えてしまったので方針的にまずければ調整が必要かもしれません。
プルリクの仕方がまずい場合は訂正します。
宜しくお願い致します。。
=> changed to qiita compatible navbar.

src/main/java/org/support/project/knowledge/control/open/FileControl.java, src/main/java/org/support/project/knowledge/logic/SlideLogic.java, src/main/webapp/WEB-INF/views/open/knowledge/partials/partials-view-attach-files.jsp, src/main/webapp/WEB-INF/views/open/knowledge/partials/partials-view-comment-edit.jsp, src/main/webapp/WEB-INF/views/open/knowledge/partials/partials-view-comment-list.jsp, src/main/webapp/WEB-INF/views/protect/knowledge/edit_comment.jsp, src/main/webapp/WEB-INF/views/protect/knowledge/partials/partials-edit-attach.jsp, src/main/webapp/js/knowledge-attachfile.js, src/main/webapp/js/knowledge-view-attachfile.js
=> Fix content type of images for inline display.

src/main/webapp/WEB-INF/views/commons/layout/commonNavbar.jsp, src/main/webapp/css/common.css
Navbarのデザインを微調整。
Addの右側の▼を推した際に「下書き」だけでなく「作成」も表示するようにした
=> #749 Change Navbar's design slightly

src/main/java/org/support/project/knowledge/parser/impl/PptxSlideShowParser.java
=> Fix PowerPoint presentations are always converted to black image.

src/main/java/org/support/project/knowledge/logic/TargetLogic.java
自分を消してしまうと、一度開いたあとで保存すると権限が消えてしまう。
（グループに入っていない場合）
=> #757 Do not erase the login user in the display of the logined user

src/main/resources/appresource.properties
Fix article. (an image/an automation)
Fix typo. (with preview)
---
冠詞の修正
Typoの修正
（width previewで合ってたらすいません）
=> Improve appresource.properties

src/main/webapp/WEB-INF/views/admin/webhook/config.jsp
Add  'for' attribute to label tag.
=> Improve usability

.gitignore, pom.xml, src/main/java/org/support/project/knowledge/Launch.java
I made it possible to start it with built-in Tomcat at development time
=> Emb tomcat

src/main/java/org/support/project/web/logic/LdapLogic.java
=> Delete the part of code that the login user searches for Base DN.

.travis.yml, pom.xml, src/main/java/org/support/project/web/logic/LdapLogic.java
Reverts support-project/knowledge#928
=> Revert "Delete the part of code that the login user searches for Base DN."
