src/main/java/org/support/project/knowledge/logic/TagLogic.java
#93 の問題を対応しました。
ご検討よろしくお願いします。
※Mac book el capitan上のtomcatで表示されるのを確認しました。
=> #93 タグ一覧の2ページ目以降が表示されない問題の対応

src/main/java/org/support/project/knowledge/bat/NotifyMailBat.java
記事の投稿または更新、参考になった、コメント追加からNotifyMailBatが起動するまでの間に記事の削除またはコメントの削除が行われた場合、データの取得ができないためnullに対してメソッド呼び出しをする形になり処理が落ちていたためnullチェックをしてnullであればスキップするようにしました。
データが取得できない場合は以下のようなログが出力されます。
```
INFO  2015-10-17 22:03:25,786 [AbstractBat(26)] NotifyMailBat is start.
INFO  2015-10-17 22:03:26,496 [DBConnenctionLogic(35)] Custom connection setting is exists.
INFO  2015-10-17 22:03:26,618 [NotifyMailBat(71)] Notify process started.
WARN  2015-10-17 22:03:27,764 [NotifyMailBat(349)] Knowledge record not found. id: 147
WARN  2015-10-17 22:03:27,876 [NotifyMailBat(128)] Knowledge record not found. id: 267
WARN  2015-10-17 22:03:27,990 [NotifyMailBat(210)] Comment record not found. id: 126
WARN  2015-10-17 22:03:27,994 [NotifyMailBat(349)] Knowledge record not found. id: 139
INFO  2015-10-17 22:03:27,996 …
```
=> #99 各通知キュー登録時にnullチェックをするように

src/main/java/org/support/project/knowledge/control/protect/FileControl.java
記事に添付されてる画像を削除できるようにしました。
確認した内容は以下です。
* 投稿したユーザが削除できること
* 共同編集が許可されてるユーザで削除できないこと
* 管理権限を持ってるユーザで削除できること
よろしくお願いします。
=>  #114 記事に添付されてる画像を削除できるように

src/main/java/org/support/project/knowledge/bat/FileParseBat.java, src/main/java/org/support/project/knowledge/entity/KnowledgeItemValuesEntity.java
bookmarkに指定されたURLに書かれた内容を取得する際にエラーが発生した場合、次のbookmarkのコンテンツを処理するように変更した
=> #137 URLの内容取得でエラーが発生した場合のハンドリング修正

src/main/java/org/support/project/knowledge/control/open/KnowledgeControl.java
=> #27 登録したナレッジのテンプレートが削除されてしまった場合、そのナレッジは通常のナレッジのテンプレートで処理するようにする

src/main/java/org/support/project/knowledge/control/open/KnowledgeControl.java, src/main/java/org/support/project/knowledge/logic/KeywordLogic.java, src/main/webapp/WEB-INF/views/commons/layout/commonNavbar.jsp, src/main/webapp/WEB-INF/views/open/knowledge/search.jsp
* 実装内容
* キーワード検索にgroups:グループ名があった場合にグループで絞った結果を出力するように
* キーワード検索にtags:タグ名があった場合にタグで絞った結果を出力するように
* groups:またはtags:を指定している状態で一覧から検索画面に遷移した場合にキーワードを分解してそれぞれのフォームに値を入れるように
=> #105 キーワード検索で検索クエリを指定できるように

src/main/java/org/support/project/knowledge/control/open/KnowledgeControl.java, src/main/java/org/support/project/knowledge/logic/GroupLogic.java, src/main/webapp/WEB-INF/views/open/knowledge/list.jsp
* 実装内容
* 投稿一覧ページに投稿順のグループ一覧と投稿数のリストを表示するように
* 見た目制御
* 未ログインユーザの場合は現状と同じくリンクのみを設置
* ログインユーザは所属グループの上位10件をリスト表示
* 管理ユーザは全グループの上位10件をリスト表示
よろしくお願いします。
@see support-project/web#8
=> #134 Knowledge一覧にグループ一覧を追加(投稿数順)

src/test/java/org/support/project/knowledge/logic/MarkdownLogicTest.java, src/test/resources/org/support/project/knowledge/logic/markdown/markdj-link.md, src/test/resources/org/support/project/knowledge/logic/markdown/result-4.txt, src/test/resources/org/support/project/knowledge/logic/markdown/result-5.txt, src/test/resources/org/support/project/knowledge/logic/markdown/result-6-2.txt, src/test/resources/org/support/project/knowledge/logic/markdown/result-6.txt, src/test/resources/org/support/project/knowledge/logic/markdown/result-markdj-1.txt, src/test/resources/org/support/project/knowledge/logic/markdown/result-markdj-link.txt
- Markdownのパース結果の外部リンクでアンカーを生成する際に、 target="_blank" を追加
- Markdownのパーサーを修正
- サニタイジング処理で target を消すのでそこも修正
- knowledgeでは、テストケースの期待値を修正するのみ
=> #151 外部リンクに `target="_blank"` の対応

src/main/java/org/support/project/knowledge/control/protect/KnowledgeControl.java, src/main/webapp/WEB-INF/views/protect/knowledge/view_add.jsp, src/main/webapp/WEB-INF/views/protect/knowledge/view_edit.jsp, src/main/webapp/js/knowledge-edit.js
- 登録／更新画面をAjaxによる保存に変更し、画面遷移を伴うデータ保存をやめた
- 画面遷移をしていたために、再度画面を表示する際の情報を再取得しなければならず、処理が複雑になっていた
- 画面遷移をなくす事で、画面上の情報をリロードする必要がなくなり、処理が簡潔になるので変更
- 画面遷移をしないようにしたので、タグの選択状態のリクエストパラメータは置換されないので、登録後に一覧の戻っても変なタグ選択状態にならないようになった
=> #119 保存後、タグの選択状態が変更されないように修正

src/main/java/org/support/project/knowledge/control/admin/WebhookControl.java, src/main/java/org/support/project/knowledge/entity/WebhookConfigsEntity.java, src/main/java/org/support/project/knowledge/logic/CrawlerLogic.java, src/main/java/org/support/project/knowledge/logic/HttpLogic.java, src/main/java/org/support/project/knowledge/logic/WebhookLogic.java, src/main/resources/appresource.properties, src/main/resources/appresource_ja.properties, src/main/resources/org/support/project/knowledge/webhook/comments.json, src/main/resources/org/support/project/knowledge/webhook/knowledges.json, src/main/webapp/WEB-INF/views/admin/webhook/config.jsp, src/main/webapp/WEB-INF/views/commons/layout/commonNavbar.jsp
#69 の管理画面追加PRです。
次のPRで実際にWebhookを実行するバッチあげます。
Proxyを通したHTTP通信を再利用したかったのでCrawlerLogicからクライアント作成ロジックを
切り出してHttpLogicとして抽象スーパークラスとしました。
一応bookmarkのFileParseBatが正常に実行されるのは確認してますが
もしお手数でなければ一度手元にpullしてご確認いただけるとありがたいです。
よろしくお願いします。
=> Webhookの管理画面を追加

bower.json
bootstrap-tagsinputをv0.7系まで利用していたバージョンに戻したところ、
#240 の問題が発生しないことを確認しました。
=> #240 タグ入力のライブラリを以前動作させていたバージョンに戻した

src/main/java/org/support/project/knowledge/control/protect/KnowledgeControl.java, src/main/java/org/support/project/knowledge/logic/GroupLogic.java, src/main/webapp/WEB-INF/views/protect/knowledge/view_add.jsp
=> #247 新規投稿時の公開範囲と共同編集者のデフォルト値の挙動を変更

src/main/java/org/support/project/knowledge/logic/CrawlerLogic.java
なんで検索にひっかからないの？という問い合わせの解析のため。
ちなみに、SSL証明書が不正だった。
=> bookmarkなknowledgeでコンテンツ取得エラーの際のログにURLを出力するようにした

src/main/webapp/WEB-INF/views/open/knowledge/view.jsp, src/main/webapp/WEB-INF/views/protect/knowledge/view_edit.jsp
#277 の対応になります。
ナレッジのIDは幅をとるため削りました。
=> 詳細、編集画面のtitleタグの先頭に記事タイトルを持ってくるように

src/main/java/org/support/project/knowledge/bat/AbstractBat.java, src/main/java/org/support/project/knowledge/bat/DataTransferBat.java, src/main/java/org/support/project/knowledge/bat/ReIndexingBat.java, src/main/java/org/support/project/knowledge/listener/GlobalInitializationListener.java, src/main/java/org/support/project/knowledge/logic/DataTransferLogic.java, src/main/java/org/support/project/knowledge/logic/MarkdownLogic.java
This pull request is focused on resolving occurrences of Sonar rules
squid:S106 - Standard outputs should not be used directly to log anything.
https://dev.eclipse.org/sonar/coding_rules#q=squid%3AS106
George Kankava
=> squid:S106 - Standard outputs should not be used directly to log anything

src/main/java/org/support/project/knowledge/control/protect/KnowledgeControl.java, src/main/java/org/support/project/knowledge/logic/GroupLogic.java, src/main/java/org/support/project/knowledge/logic/KeywordLogic.java, src/main/java/org/support/project/knowledge/logic/KnowledgeLogic.java, src/main/java/org/support/project/knowledge/logic/TemplateLogic.java, src/main/java/org/support/project/knowledge/parser/impl/TextParser.java
This pull request is focused on resolving occurrences of Sonar rules
squid:S1226 - Method parameters, caught exceptions and foreach variables should not be reassigned.
squid:S1488 - Local Variables should not be declared and then immediately returned or thrown.
https://dev.eclipse.org/sonar/coding_rules#q=squid%3AS1226
https://dev.eclipse.org/sonar/coding_rules#q=S1488|rule_key=squid%3AS1488
George Kankava
=> squid:S1226 - Method parameters, caught exceptions and foreach variables should not be reassigned

src/main/java/org/support/project/knowledge/dao/KnowledgesDao.java, src/main/java/org/support/project/knowledge/dao/NotifyConfigsDao.java, src/main/java/org/support/project/knowledge/dao/TagsDao.java, src/main/java/org/support/project/knowledge/dao/TemplateMastersDao.java, src/main/java/org/support/project/knowledge/dao/WebhookConfigsDao.java
This pull request is focused on resolving occurrence of Sonar rule
squid:S1213 - The members of an interface declaration or class should appear in a pre-defined order.
https://dev.eclipse.org/sonar/rules/show/squid:S1213
George Kankava
=> squid:S1213 - The members of an interface declaration or class should appear in a pre-defined order

src/main/java/org/support/project/knowledge/entity/TemplateItemsEntity.java, src/main/java/org/support/project/knowledge/entity/TemplateMastersEntity.java
This pull request is focused on resolving occurrence of Sonar rule
squid:S1488 - Local Variables should not be declared and then immediately returned or thrown.
https://dev.eclipse.org/sonar/rules/show/squid:S1488
George Kankava
=> squid:S1488 - Local Variables should not be declared and then immediately returned or thrown

src/main/java/org/support/project/knowledge/control/protect/ConfigControl.java, src/main/java/org/support/project/knowledge/control/protect/GroupControl.java, src/main/java/org/support/project/knowledge/control/protect/KnowledgeControl.java, src/main/java/org/support/project/knowledge/control/protect/StockControl.java
This pull request is focused on resolving occurrences of Sonar rules
squid:S1068 - Unused private fields should be removed.
squid:S1905 - Redundant casts should not be used.
https://dev.eclipse.org/sonar/rules/show/squid:S1068
https://dev.eclipse.org/sonar/rules/show/squid:S1905
George Kankava
=> Multiple code improvements - squid:S1068, squid:S1905

src/main/webapp/WEB-INF/views/protect/knowledge/view_add.jsp, src/main/webapp/WEB-INF/views/protect/knowledge/view_edit.jsp, src/main/webapp/css/knowledge-edit.css, src/main/webapp/js/knowledge-edit.js
時間が空いてしまったのですが #281 の編集画面のデザイン変更です。
編集領域を極力上に持ってきてpreviewしやすくタブ化してみました。
=> 編集画面のデザイン変更

Procfile, README.md, app.json, package.json, pom.xml
#329 にて、デモ環境の問題があったようなので、Heroku ButtonでHerokuへ簡単にデプロイできるようにしてみました。
[kaakaa/knowledge at heroku](https://github.com/kaakaa/knowledge/tree/heroku) より試せます。
Heroku上でのknowledge.warの起動にはWebapp Runnerを使用しています。
[Deploying Tomcat-based Java Web Applications with Webapp Runner | Heroku Dev Center](https://devcenter.heroku.com/articles/java-webapp-runner#deploying-with-the-heroku-maven-plugin)
もし、マージしていただける場合は、`README.md`に書かれているHeroku Buttonのリンクを修正するよう留意ください。
`[![Deploy](https://www.herokucdn.com/deploy/button.svg)](https://heroku.com/deploy?template=https://github.com/kaakaa/knowledge/tree/heroku)`
↓
`[![Deploy](https://www.herokucdn.com/deploy/button.svg)](https://heroku.com/deploy?template=https://github.com/support-project/knowledge)`
* * * 
また、Herokuへデプロイする際はHeroku上のMavenビルドで`bower …
=> Heroku Buttonの設置

src/main/webapp/WEB-INF/views/open/knowledge/list.jsp
- 通知処理を呼び出すのがセッション毎に1回になっていたが、セッションはかなり長く保持するので、新しい通知が表示されない
- セッション毎に1回にするのは、ログインしていないユーザ（既読の管理が出来ないユーザ）にする
- 既読管理しているユーザは通知があるかはチェックするようにする
=> #113 fix call notify method timing

src/test/java/org/support/project/knowledge/logic/MarkdownLogicTest.java
UNCパスや、file:// 、smb:// へのリンクが、サニタイズの処理の中で消していたため、
出力できるように修正した。（webモジュールの修正で、テストを追加したのみ）
=> Modify Sanitize process that outputs a unc path.

pom.xml, src/test/java/org/support/project/knowledge/logic/MarkdownLogicTest.java
Markdownのパース処理の中で、「＆」の置換を間違えていたので、Markdownパーサーの方を修正した。
それに伴い、参照先のライブラリバージョンの更新とテストを追記した。
=> Add test for amp

src/main/webapp/js/slide.js
社内でスライドのページネーション操作をキーボードで行いたいという要望があったため実装してみました。
複数のスライドが表示されることを想定してマウスカーソルがスライド内にある場合のみそのスライドのページネーション操作をできるようにしています。
=> Add slide paginate key event

src/main/java/org/support/project/knowledge/control/open/KnowledgeControl.java, src/main/webapp/js/knowledge-view.js
現状だとGETでできてしまうため、ブラウザ上でリンクを何回もF5アタックする等で不用意にいいねがついてしまうのでPOSTに変更しました。
=> Fixed like http method

src/main/webapp/WEB-INF/views/open/knowledge/search.jsp, src/main/webapp/WEB-INF/views/protect/knowledge/partials/partials-edit-scripts.jsp, src/main/webapp/js/common.js, src/main/webapp/js/knowledge-target-select.js
#271 に関連して、タグ名とグループ名が自動補完された場合に文字参照で補完されてしまうのを修正しました。
unescapeHTML 関数については、[こちら](http://blog.tojiru.net/article/211339637.html)のコードを利用させて頂いています。
いろいろ触ってみて気づいた箇所を修正しましたが、他にも修正するべき点がありましたらご指摘ください。
=> Fix auto-completed tagnames and groupnames are html-escaped.

src/main/java/org/support/project/knowledge/logic/KnowledgeLogic.java
最近タグ名検索を直したので気になって調べました。
#731 について、直接の原因は KnowledgeControl の 401 行目で、タグ名検索またはグループ名検索のときに List を new でインスタンス生成しているため、KnowledgeLogic の
```java
if (groups != null) {
for (GroupsEntity groupsEntity : groups) {
searchingValue.addGroup(groupsEntity.getGroupId());
}
return searchKnowledge(searchingValue);
}
```
で return してしまっていたためのようです。
KnowledgeControl でグループ名がないときは List インスタンスを生成しないように修正してもいいかと思いましたが、KnowledgeLogic の少し上に
```java
if (tags != null && !tags.isEmpty()) {
for (TagsEntity tagsEntity : tags) {
searchingValue.addTag(tagsEntity.getTagId());
}
}
```
とあったので、IF 条件判定文を直しました。
なお、グループ名検索については問題ないように見えました。
=> #731 fix unauthorized items are listed when user searchs with tag names.

src/main/webapp/WEB-INF/views/commons/layout/commonNavbar.jsp, src/main/webapp/css/common.css
レスポンシブで横幅が狭くなった時にナビバーがつぶれてしまう問題を少し対処しました。
- ドロップダウンを展開すると子メニューが見えなくなる問題の対処
- ボタンの上下余白が若干サーチバーとずれる部分の修正
- ストックとユーザーメニューに色が付いてなかったのを色をつけるように変更
「スマートフォンで見たときにボタンを押し安くする」ですが私のbootstrapの知識ではいい方法が思いつかず今回はスルーしました、すいません。
=> fix navbar layout collapse.

src/main/webapp/css/slide.css, src/main/webapp/js/slide.js
#725 に関連して、fade クラスが bootstrap と slide.css で重複していたので修正しました。
slide.css の fade は slide.js 以外では使用していない認識ですが、修正不足があればお知らせください。
=> Fix overlapped style class.

src/main/webapp/js/common.js
ストックボタンをクリックすると、ダイアログが出ている間だけスクロールバーが消えて、ナビゲーションバーがずれるのが前から気になっていて調べました（他のダイアログも同様）。
https://github.com/twbs/bootstrap/issues/14040
がこの事象と一致すると思うのですが、Bootstrap 3 系はもう修正しないようなので、このページに載っていたワークアラウンドで対処しました。
主要なブラウザの最新版では動作確認済みです。
Bootstrap jQuery Modal を拡張しているコードなので他に影響はないのではないかと考えています。
=> Fix when modal dialog open, navbar slides slightly.

src/main/webapp/js/common.js, src/main/webapp/js/knowledge-attachfile.js, src/main/webapp/js/knowledge-view-attachfile.js
#810 に対してパッチを書きました。
この動作を確認いただいて、何か気になる点があれば再修正していきたい考えです。
* ブラウザ全体が画像のドロップターゲットでしたが、それを指定されたエリアだけに変更しました。
* 上記修正により、指定エリア以外に画像をドロップすると、ブラウザのデフォルトの挙動でローカルの画像ファイルが開くようになってしまったので、その挙動を抑止しました。
IE11/Edge/Firefox/Chrome/Safari （すべて現在の最新版）で動作確認済みです。
=> fix drop target of images.

src/main/java/org/support/project/knowledge/control/open/KnowledgeControl.java, src/main/java/org/support/project/knowledge/control/protect/KnowledgeControl.java, src/main/java/org/support/project/knowledge/logic/TargetLogic.java
#757 の対応になります。
そのユーザがナレッジに指定されてるグループに所属してる場合はラベルを表示しないようにしています。
また更新側に影響が出ないようにメソッドを切り出してそちらを呼ぶようにしました。
https://github.com/support-project/web/pull/76 に依存しているのでこちらもご確認お願いします。
=> #757 fix target labels

src/main/webapp/css/common.css
Don't display URL when printing.
=> Improve print stylesheet

src/main/webapp/js/slide.js
#860 に関して、矢印キーを押したときは keypress イベントが Firefox 以外では起動しなかったことが原因のようです。
=> Fix keypress events does not fired on pushing arrow keys.

src/main/webapp/WEB-INF/views/commons/layout/commonNavbar.jsp
ヘッダーの作成ボタンのドロップダウンをクリックしたとき、隣のボタンの背景色が白っぽくなって見づらくなっていたのが気になっていたので、色が変わらないように修正しました。
HTML 上で nav クラスの子孫に a タグがあると、bootstrap.css の
```css
.nav .open > a,
.nav .open > a:hover,
.nav .open > a:focus {
background-color: （テーマによって異なる）
border-color: （テーマによって異なる）
}
```
の部分がドロップダウンをクリックしたときに有効化されてしまって、その結果、背景色が変わるようでした。ここを common.css 等で上書きしても全テーマで同じ背景色になってしまうため、PR のように a タグを button タグに変更する方法を採用しました。
その際、tabindex を無効化しています。Tab キーを押したときの遷移はOS/ブラウザによって挙動が異なるようでしたのでどうするべきか迷いましたが、作成ボタンとドロップダウン２つで１つかと思い、ドロップダウンのみ Tab キーで遷移するようにしています。
=> Fix when Add dropdown is clicked, Add button becomes hard to see.

src/main/resources/appresource.properties
英語リソースのアポストロフィが原因でJavaScriptが解釈されないため
文字参照に置き換え、改行タグ追加
=> Fix the problem where don't work JavaScript when delete a user on English mode

src/main/webapp/css/markdown.css
Horizontal scrollbar appears by long URL text.
Change to wrap URL.
=> Change to wrap URL

src/main/webapp/js/knowledge-view-toc.js
When click the table of contents,  title hides behind navbar.
ex. select タイトル2.
before
after
=> Improve jump position from table of contents
